package tifmo

/**
 * This package provides a way to generate on-the-fly knowledge.
 * 
 * You need: (i) an [[tifmo.inference.IEngine]], and add premises and hypotheses and 
 * linguistic knowledge; (ii) an [[tifmo.onthefly.AEngine]], and add premises and 
 * hypotheses; and (iii) construct an [[tifmo.onthefly.OnTheFly]], which provides 
 * an interface for you to try generated on-the-fly knowledge. 
 * 
 * In details, on-the-fly knowledge is generated like this: 
 * 
 * (i) Firstly, [[tifmo.onthefly.AEngine]] takes a set of 
 * [[tifmo.dcstree.Declarative]]s as premise, and will do abduction for each goal 
 * (represented also by [[tifmo.dcstree.Declarative]]), to produce assumptions 
 * that may be helpful to prove the goal.
 * 
 * (ii) Secondly, the function object `alignPaths` can takes assumptions 
 * generated by an [[tifmo.onthefly.AEngine]] and produces path alignments. These 
 * path alignments are intuitive tree transformations motivated by the assumptions, 
 * but may or may not generate the knowledge that implies the assumptions.
 * 
 * (iii) Thirdly, filter or evaluate these path alignments.
 * 
 * (iv) Finally, each path alignment can generate a piece of on-the-fly knowledge. 
 */
package object onthefly {}
